INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Experience the epic sci-fi saga of Commander Shepard as you navigate through a galaxy on the brink of annihilation.', 'The Mass Effect Trilogy combines all three installments of the award-winning series into one immersive experience. Lead your team across a richly detailed universe where your decisions have profound consequences on the story and the fate of the galaxy. Engage in intense combat, build relationships, and face the looming threat of the Reapers.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Open World, Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Step into the boots of Arthur Morgan in a tale of loyalty, conviction, and the price of infamy.', 'Red Dead Redemption 2 is an epic tale of life in America at the dawn of the modern age. As Arthur Morgan, a senior member of the Van der Linde gang, navigate the rugged heartland of America, facing federal agents and bounty hunters. The game offers a vast and atmospheric world, providing the foundation for a new online multiplayer experience.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Embark on a dark fantasy journey as Geralt of Rivia, a monster hunter searching for his missing adopted daughter.', 'The Witcher 3: Wild Hunt is a story-driven open-world RPG set in a visually stunning universe full of meaningful choices and impactful consequences. In The Witcher, you play as professional monster hunter Geralt of Rivia, tasked with finding a child of prophecy in a vast open world rich with merchant cities, pirate islands, dangerous mountain passes, and forgotten caverns to explore.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Take on the role of the "one-armed wolf" in a brutal journey of vengeance during the Sengoku period in Japan.', 'Sekiro: Shadows Die Twice is a third-person, action-adventure game with RPG elements. It focuses on stealth, exploration, and combat, featuring a variety of prosthetic tools and abilities. Players experience a dark and twisted world as they face formidable foes in a quest to rescue their kidnapped lord and exact revenge on their enemies.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Action-Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Become Jin Sakai, a samurai warrior defending Tsushima Island during the Mongol invasion.', 'Ghost of Tsushima is an open-world action-adventure game set in feudal Japan. Players control Jin Sakai, a samurai on a quest to protect Tsushima Island from the Mongol invasion. The game features a vast open world without waypoints, allowing players to explore and discover missions and activities organically.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Join Mario and Luigi on a quest to save Dinosaur Land from the evil Bowser.', 'Super Mario World is a 2D side-scrolling platform game where players control Mario or Luigi. The game introduces Yoshi, a dinosaur companion, and features 96 levels across seven worlds. Players must navigate through various terrains, avoiding obstacles and enemies, to rescue Princess Toadstool and save Dinosaur Land.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore the vast, ruined kingdom of Hallownest in this challenging action-adventure.', 'Hollow Knight is a 2D action-adventure game set in Hallownest, a vast, interconnected, ruined kingdom. Players control the Knight as they explore caverns, ancient cities, and deadly wastes, battle tainted creatures, and befriend bizarre bugs, all in a classic, hand-drawn 2D style.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Embark on a visually stunning journey in a forest filled with peril in this heartfelt adventure.', 'Ori and the Blind Forest is a visually stunning action-platformer that tells the tale of a young orphan destined for heroics. The game features hand-painted artwork, meticulously animated character performances, and a fully orchestrated score, offering a deeply emotional story about love, sacrifice, and hope.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Engage in relentless boss battles in this 1930s cartoon-inspired run-and-gun game.', 'Cuphead is a classic run-and-gun action game heavily focused on boss battles. Inspired by 1930s cartoons, the visuals and audio are painstakingly created with the same techniques of the era, including traditional hand-drawn cel animation, watercolor backgrounds, and original jazz recordings.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Join Sonic in a time-traveling adventure to save Little Planet from Dr. Robotnik.', 'Sonic CD is a 2D platform game where players control Sonic the Hedgehog as he attempts to save the mystical Little Planet from Dr. Robotnik. The game introduces time travel, allowing players to access different versions of levels (past, present, and future) and features the debut of characters like Amy Rose and Metal Sonic.');

INSERT INTO tb_game_list (name) VALUES ('Sandbox, Adventure, RPG');
INSERT INTO tb_game_list (name) VALUES ('Plataform');


INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);